const mongoose=require('mongoose');
const Schema=mongoose.Schema;
const liveclassSchema=new Schema(
    {
        classname:{
            type:String,
            required:true,
        },
        sdateandtime:{
            type:String,
            required:true,
        },
        description:{
            type:String,
            required:true,
        },
        image:{
            type:String,
            required:true,
        },
        classtype:{
            type:String,
        },
        approval:{
            type:String,
        },
        access:{
            type:String,
        },
        price:{
            type:String,
        },
        category:{
            type:String,
        },
        instructor:{
            name:{type:String},
            iimg:{type:String},
        },
        duration:{
            type:String,
        },
        caloriesburnt:{
            type:String,
        },
        instructorprofile:{
            type:String,
        },
        snameandcount:{
            type:String,
        },
    },
    {
        timestamps:true,
    }
);
const Liveclass=mongoose.model('Liveclass',liveclassSchema);
module.exports=Liveclass;