const mongoose=require('mongoose');
const Schema=mongoose.Schema;
const programSchema=new Schema(
    {
        classname:{
            type:String,
            required:true,
        },
        sdateandtime:{
            type:String,
            required:true,
        },
        description:{
            type:String,
            required:true,
        },
        duration:{
            type:String,
        },
        image:{
            type:String,
            required:true,
        },
        exercise:{
            exercisename:{type:String},
            video:{type:String},
            category:[
                {
                    categoryname:{type:String},
                    cimage:{type:String},
                    caloriesburnt:{type:String},
                }
            ]
        },
        totalexercises:{
            type:String,
        },
        classtype:{
            type:String,
        },
        approval:{
            type:String,
        },
        chooseinstructor:{
            type:String,
        },
        instructorprofile:{
            type:String,
        },
        access:{
            type:String,
        },
        price:{
            type:String,
        },
        category:{
            type:String,
        },
        pmaterial:{
            type:String,
        },
        status:{
            type:String,
        },
        subscribe:{
            type:String
        }
    },
    {
        timestamps:true,
    }
);
const Program=mongoose.model('Program',programSchema);
module.exports=Program;